# Generated by Django 4.2.6 on 2023-12-06 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_articles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='name',
            field=models.TextField(max_length=150, verbose_name='Название'),
        ),
    ]
