# Generated by Django 4.2.6 on 2023-12-06 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_articles_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='direction',
            field=models.ManyToManyField(null=True, to='courses.direction'),
        ),
    ]
