# Generated by Django 4.2.6 on 2023-12-08 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_course_direction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Otziv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Имя')),
                ('profession', models.CharField(max_length=120, verbose_name='Профессия')),
                ('text', models.TextField(verbose_name='Текст комментария')),
                ('img', models.ImageField(default='otziv.jpg', upload_to='otziv_img')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
