# Generated by Django 4.2.6 on 2024-01-07 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_direction_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direction',
            name='slug',
            field=models.SlugField(),
        ),
    ]
